<?php
/*********************************************************************************
 *       Filename: styles.inc
 *       Generated with CodeCharge 2.0.5
 *       PHP 4.0 build 11/30/2001
 *********************************************************************************/
$styles = array();

$styles["PageBODY"] = "bgcolor=\"#CDCEDC\" text=\"#000000\" link=\"#000080\" vlink=\"#000080\" alink=\"#000080\"";
$styles["FormTABLE"] = "border=\"1\" cellspacing=\"0\" bordercolor=\"#BCBC7A\" bordercolorlight=\"#000000\" bordercolordark=\"#FFFFFF\"";
$styles["FormHeaderTD"] = "align=\"center\" bgcolor=\"#666633\"";
$styles["FormHeaderFONT"] = "style=\"font-size: 12pt; color: #FFFFFF; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
$styles["FieldCaptionTD"] = "bgcolor=\"#BCBC7A\"";
$styles["FieldCaptionFONT"] = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica\"";
$styles["DataTD"] = "bgcolor=\"#DDDDBD\"";
$styles["RecordSeparatorTD"] = "bgcolor=\"#DDDDBD\"";
$styles["DataFONT"] = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica\"";
$styles["ErrorFONT"] = "style=\"font-size: 10pt; color: #FF0000; font-family: Arial, Tahoma, Verdana, Helvetica\"";
$styles["ColumnFONT"] = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
$styles["ColumnTD"] = "bgcolor=\"#BCBC7A\"";
?>